apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homer-cert
  namespace: {{index . "namespace"}}
spec:
  dnsNames:
    - homer.{{ index . "domain"}}
  secretName: homer-cert
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer

